version: "3.8"
services:
    nginx-php:
        depends_on: 
            - php-game
        build:
            dockerfile: Dockerfile.nginx
            context: ./nginx
        ports:
            - '80:80'
    php-game:
        build:
            dockerfile: Dockerfile.gameEmagia
            context: .
        volumes:
            - /var/www/html/vendor
            - ./gameEmagia:/var/www/html/
    php-game-test:
        build:
            dockerfile: Dockerfile.gameEmagia
            context: .
        volumes:
            - /var/www/html/vendor
            - ./gameEmagia:/var/www/html/
        command: ["./vendor/bin/phpunit", "tests"]
    

